model_list:
  - model_name: xai/*
    litellm_params:
      model: xai/*

litellm_settings:
  # Logging/Callback settings
  success_callback: ["langfuse"]

general_settings:
  store_prompts_in_spend_logs: true
